# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  # Enable strict mode for better type safety
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Treat these as errors instead of warnings
    missing_required_param: error
    missing_return: error
    dead_code: error
    unused_element: error
    unused_field: error
    unused_import: error
    unused_local_variable: error
    invalid_annotation_target: error
    # Additional errors for stricter enforcement
    parameter_assignments: error
    deprecated_member_use: error
    deprecated_member_use_from_same_package: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "**/build/**"

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # === STRICT TYPE CHECKING ===
    always_declare_return_types: true
    always_specify_types: true
    type_annotate_public_apis: true
    avoid_annotating_with_dynamic: true
    implicit_call_tearoffs: true

    # === ERROR PREVENTION ===
    # Potential bugs
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    valid_regexps: true

    # Async/await safety
    avoid_returning_null_for_void: true
    unawaited_futures: true

    # Collections
    avoid_function_literals_in_foreach_calls: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true

    # Null safety
    avoid_null_checks_in_equality_operators: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true

    # === CODE QUALITY & STYLE ===
    # Const correctness
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true

    # Finals
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true

    # String handling
    prefer_single_quotes: true
    prefer_adjacent_string_concatenation: true
    prefer_interpolation_to_compose_strings: true
    prefer_raw_string_literals: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true

    # === NAMING CONVENTIONS ===
    camel_case_types: true
    camel_case_extensions: true
    constant_identifier_names: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    package_prefixed_library_names: true

    # === CLARITY & CONSISTENCY ===
    # Code organization
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    directives_ordering: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    # Simplification
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: false  # Sometimes we need generic catches
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true

    # Unnecessary code
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true

    # === BEST PRACTICES ===
    # Control flow
    curly_braces_in_flow_control_structures: true
    exhaustive_cases: true
    no_default_cases: false  # Allow default cases for extensibility
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_inlined_adds: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true

    # Class design
    avoid_classes_with_only_static_members: true
    one_member_abstracts: true
    prefer_constructors_over_static_methods: true
    prefer_mixin: true
    use_super_parameters: true
    use_enums: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_setters_to_change_properties: true
    use_to_and_as_if_applicable: true

    # Flutter specific
    avoid_web_libraries_in_flutter: true
    use_build_context_synchronously: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true

    # Testing
    avoid_relative_lib_imports: true
    depend_on_referenced_packages: true
    package_names: true
    secure_pubspec_urls: true

    # === DOCUMENTATION ===
    # Set to true to enforce documentation on all public APIs
    public_member_api_docs: false
    # Uncomment these for stricter documentation requirements:
    # comment_references: true
    # package_api_docs: true
    # provide_deprecation_message: true

    # === PERFORMANCE ===
    avoid_field_initializers_in_const_classes: true
    control_flow_in_finally: true
    literal_only_boolean_expressions: true
    no_leading_underscores_for_local_identifiers: true
    no_logic_in_create_state: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    test_types_in_equals: true
    use_string_buffers: true

    # === EXPERIMENTAL/PEDANTIC ===
    # Uncomment for even stricter enforcement:
    # cascade_invocations: true
    # join_return_with_assignment: true
    # leading_newlines_in_multiline_strings: true
    # lines_longer_than_80_chars: true
    # missing_whitespace_between_adjacent_strings: true
    # only_throw_errors: true
    # prefer_expression_function_bodies: true
    # sort_pub_dependencies: true
    # use_string_in_part_of_directives: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
